name: Deploy to InfinityFree

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Deploy backend
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./
          server-dir: /htdocs/
          exclude: |
            .git/**
            .github/**
            .env
            .htaccess
      
      - name: Run PHP
        run: |
          php command cache:config
          php command dump-autoload -c
          php -r "echo 'PHP works: ' . PHP_VERSION . PHP_EOL;"